import type { Metadata } from "next";

import "../../public/styles/globals.css";
import Navbar from "./_Components/navbar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fr">
            <body className="container mx-auto flex flex-col items-center justify-center">
                <Navbar />
                {children}
            </body>
        </html>
    );
}
